exclude: >
    (?x)(
        ^.*\b(migrations)\b.*$
    )

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
      - id: pyupgrade
        args: [--py3-plus, --py38-plus]

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [--safe, --quiet, --line-length=79]

  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args:
          - --max-line-length=79
          - --ignore=E203,E501,C901,PD901,VNE001,D102,D103,W503,E402,D105,D101,E722
          - --docstring-convention=numpy
          - --max-function-length=35
        additional_dependencies:
          # - flake8-assert-msg==1.1.1
          # - flake8-builtins==1.4.1
          # - flake8-comprehensions==1.4.1
          - flake8-functions==0.0.2
          # - pandas-vet==0.2.3
          - pep8-naming==0.12.1
          - flake8-docstrings==1.6.0
