title = "Setup TOML"

[paths]
chromedriver = ""
database = "gpu_db.json"

[driver_options]
disable_gpu = "True"

[scraper]
start_url = "https://www.ebay.co.uk/b/Computer-Graphics-Video-Cards/27386/bn_661667?LH_ItemCondition=3000&LH_PrefLoc=1&LH_Sold=1&rt=nc&_sop=13&_udlo=10"

[sleeps]
starting_web_driver = 3

[num_results]
min = 20
max = 5000

[date_limit]
oldest = "2021-01-01"

[filters]
accepted_substrings = [ "GTX", "RTX",]
