# Generated by Django 3.2.10 on 2021-12-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visualisation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graphicscard",
            name="launch_price",
            field=models.IntegerField(verbose_name="Launch price ($)"),
        ),
    ]
