# Generated by Django 3.2.10 on 2021-12-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visualisation", "0002_alter_graphicscard_launch_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="graphicscard",
            name="super",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="graphicscard",
            name="super_restrict",
            field=models.BooleanField(default=False),
        ),
    ]
