# Generated by Django 3.2.10 on 2021-12-24 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visualisation", "0004_auto_20211224_1521"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="sale",
            unique_together=set(),
        ),
    ]
