# Generated by Django 3.2.10 on 2021-12-19 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="nvidiageneration",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="ebaygraphicscard",
            name="model",
        ),
        migrations.DeleteModel(
            name="GraphicsCard",
        ),
        migrations.DeleteModel(
            name="NvidiaGeneration",
        ),
    ]
