# Generated by Django 3.2.10 on 2021-12-28 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0002_auto_20211219_1553"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brandmenu",
            name="log",
        ),
        migrations.AddField(
            model_name="brandmenu",
            name="first_log",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="first_log",
                to="scraper.log",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="brandmenu",
            name="latest_log",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="latest_log",
                to="scraper.log",
            ),
            preserve_default=False,
        ),
    ]
